import { LostFoundPost, PostType, PostStatus, Claim } from '../types';

export const mockPosts: LostFoundPost[] = [
  {
    id: '1',
    type: PostType.Found,
    title: 'Leather Wallet',
    imageUrl: 'https://picsum.photos/seed/wallet/400/300',
    location: 'Central Library',
    date: new Date('2023-10-26T10:00:00Z').toISOString(),
    details: 'A brown leather wallet was found near the main entrance. Contains various cards but no cash. Please describe the contents to claim.',
    status: PostStatus.Pending,
    posterUid: 'admin-user',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    type: PostType.Lost,
    title: 'AirPods Pro Case',
    imageUrl: 'https://picsum.photos/seed/airpods/400/300',
    location: 'Student Union, 2nd Floor',
    date: new Date('2023-10-25T15:30:00Z').toISOString(),
    details: 'Lost my AirPods Pro charging case, it has a small scratch on the front. The earbuds are not inside. It is very important to me.',
    status: PostStatus.Pending,
    posterUid: 'some-user-1',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    type: PostType.Found,
    title: 'Blue Hydro Flask',
    imageUrl: 'https://picsum.photos/seed/flask/400/300',
    location: 'Campus Gym',
    date: new Date('2023-10-27T18:00:00Z').toISOString(),
    details: 'Found a blue Hydro Flask water bottle covered in various stickers. Left at the front desk.',
    status: PostStatus.Pending,
    posterUid: 'admin-user',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    type: PostType.Lost,
    title: 'Keys on a Red Lanyard',
    imageUrl: 'https://picsum.photos/seed/keys/400/300',
    location: 'Parking Lot C',
    date: new Date('2023-10-27T08:00:00Z').toISOString(),
    details: 'Lost a set of keys on a bright red university-branded lanyard. Has a car key and two smaller keys.',
    status: PostStatus.Pending,
    posterUid: 'some-user-2',
    createdAt: new Date().toISOString(),
  },
    {
    id: '5',
    type: PostType.Found,
    title: 'iPhone 14 Pro',
    imageUrl: 'https://picsum.photos/seed/iphone/400/300',
    location: 'Lecture Hall B101',
    date: new Date('2023-10-28T11:00:00Z').toISOString(),
    details: 'An iPhone 14 Pro with a clear case was left in the lecture hall after the 10am class. The lock screen shows a picture of a golden retriever.',
    status: PostStatus.Claimed,
    posterUid: 'admin-user',
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    type: PostType.Lost,
    title: 'Calculus Textbook',
    imageUrl: 'https://picsum.photos/seed/book/400/300',
    location: 'Cafe on Campus',
    date: new Date('2023-10-24T13:00:00Z').toISOString(),
    details: '"Calculus: Early Transcendentals", 8th Edition. My name is written inside the front cover. I really need it for my final exam.',
    status: PostStatus.Returned,
    posterUid: 'some-user-3',
    createdAt: new Date().toISOString(),
  },
];

export const mockClaims: Claim[] = [];
